# Generated by Django 4.2 on 2023-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(),
        ),
    ]
